We are working on the RRE CLI MVP.

Important:
Do not remove validation.
Do not change the replay logic.
Do not rewrite unrelated files.
Do not change existing command names.

Current problem:
QA needs to test validation pass and validation fail scenarios
using different SQLite files generated by Recorder Engine.

Current validation flow:
RRE reads recorded site config from SQLite:
SiteInformation.site_json

RRE fetches target site config from:
GET {target_url}/sites/{site_id}

Validation compares recorded config vs target config.

Requirement:
Add config-based mock target support.

The mock-server should be able to return target site config
from one of these sources:

1. sqlite
   Read SiteInformation.site_json from the same recording SQLite file.
   This is used for validation PASS testing.

2. file
   Read target site config from a JSON file.
   This is used for validation FAIL testing by giving wrong/mismatched config.

Expected config file example:

{
  "recording_file": "data/recording_001.sqlite",
  "target_url": "http://localhost:8080",
  "site_id": "b3489888-aacf-4451-893c-d7d994240f93",
  "mock_server": {
    "port": 8080,
    "site_config_source": "sqlite",
    "site_config_file": ""
  }
}

And fail example:

{
  "recording_file": "data/recording_001.sqlite",
  "target_url": "http://localhost:8080",
  "site_id": "b3489888-aacf-4451-893c-d7d994240f93",
  "mock_server": {
    "port": 8080,
    "site_config_source": "file",
    "site_config_file": "configs/wrong_site_config.json"
  }
}

Commands should support:

rre mock-server -config configs/pass_config.json
rre validate -config configs/pass_config.json
rre play -config configs/pass_config.json

Also keep old CLI flags working:
rre validate -file ... -target-url ... -site-id ...
rre play -file ... -target-url ... -site-id ...
rre mock-server -port 8080

Implementation guidance:
1. Add config model and loader.
2. Add -config flag in args.go.
3. If -config is given, use values from config file.
4. Update mocktarget.StartServer to accept mock server options.
5. In sqlite mode, mock-server reads SiteInformation.site_json
   from the recording SQLite file.
6. In file mode, mock-server reads site config from JSON file.
7. HandlerGetSite should return that loaded config.
8. Do not hardcode old SITE-001 config only.
9. Add clear errors if config is missing or invalid.
10. Run gofmt and go test ./...

Please implement in small safe changes.