Responsive and centered UI requirement:
- Preserve the current full-screen application layout.
- Keep the main content area horizontally centered within the page.
- Use a responsive max-width container so the content remains readable on large monitors without stretching excessively.
- Make the UI responsive across common laptop and monitor resolutions.
- Use flexible widths, responsive spacing, and sensible breakpoints.
- Avoid rigid fixed widths that cause overflow or excessive empty space.
- The Target URL row, site dropdown, recording area, validation panel, and Play button must remain usable at smaller widths.
- On narrower screens, allow rows to stack vertically where needed.
- Keep the header full width, while the main form content remains centered.
- Do not redesign the UI or change the established visual structure; only improve centering and responsiveness while implementing this subtask.